Develop
iLesnoy/Intern pull request #1
Opened 2022-10-16 18:06 UTC by iLesnoy

2022-10-17 16:00 UTC, viktor-dobroselsky requested changes

2022-10-17 16:00 UTC, viktor-dobroselsky commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:2.6.6'
Эту штуковину убираем. Иначе не интересно.  Я ж уже писал по поводу чистого хибера

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/model/Category.java
>      private String parent_category;
Что за нейминг?

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/model/Company.java
>  @Data
Прям не рекоммендую ставить `@Data` над сущностями. Они могут тебе при вызове hashCode или икволсвытянуть все зависимые сущности

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/model/Position.java
> +        created = LocalDateTime.parse(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
Я что-то не понимаю: ты выгоняешь строку из now(), а потом опять эту строку парсишь в LocalDateTime?  Зачем?

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/service/dto/CategoryDto.java
> +    private String parent_category;
Нейминг. В json bcgjkmpeq кэмел кейс

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/service/dto/CustomPage.java
> +    @JsonProperty("total-elements")
Придерживайся одного стиля нейминга. То у тебя андерскор, то тире

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/web/controller/CategoryController.java
> +    public CategoryDto create(@RequestBody CategoryDto categoryDto) {
Пожалуйста, разбивай сущности на request и response. Не все поля, что у тебя в request, будут в response, и наоборот

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/web/controller/CategoryController.java
> +    public CategoryDto update(@PathVariable BigInteger id, @RequestBody CategoryDto categoryDto){
Забыл валидацию body

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/web/controller/CategoryController.java
> +    @ResponseStatus(HttpStatus.OK)
Это дефолтный ответ. Аннотация не обязательна

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/resources/db/changelog/db.changelog-dev.yaml
> +databaseChangeLog:
Не рекомендую использовать yml формат для миграций. Лучше xml - проще читать

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/resources/db/changelog/db.changelog-master.yaml
> + # - include:
Не оставляй мусор

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/test/resources/init.sql
> +create table roles
Зачем это, если у тебя есть миграции в основе?

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/test/java/com/petrovskiy/mds/web/controller/WireMockInitializer.java
> +public class WireMockInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
Он тебе пока не нужен

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/test/java/com/petrovskiy/mds/web/controller/UserControllerTest.java
> +                                .withBody("[{\"userId\": 1,\"id\": 1,\"title\": \"Learn Spring Boot 3.0\", \"completed\": false}," +
Больше так не делай. Если хочешь проверить нормально тело - используй RestAssure и вытяни оттуда объект

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/test/java/com/petrovskiy/mds/dao/impl/AbstractContainerBaseTest.java
> +        postgreSQLContainer.withPassword("12345");
Хм, не нравится мне, что у тебя здесь захардкожены значения. Лучше вначале запусти конт, потом из конта вытащи юзер/пасс/базу/урл и сконфигурь тестовый контекст

2022-10-17 16:00 UTC, viktor-dobroselsky commented on src/main/resources/db/changelog/db.changelog-dev.yaml
> +databaseChangeLog:
У тебя test в основном класпасе. Почему?

2022-10-17 19:13 UTC, iLesnoy commented on src/main/java/com/petrovskiy/mds/model/Position.java
> +        created = LocalDateTime.parse(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
String text = date.format(formatter); 
приходится повторно парсить

2022-10-17 19:20 UTC, iLesnoy commented on src/test/resources/init.sql
> +create table roles
/*postgreSQLContainer.withInitScript("init.sql");*/
скрипт для котн

2022-10-17 19:22 UTC, viktor-dobroselsky commented on src/test/resources/init.sql
> +create table roles
Так у тебя в основе лежит скрипт с миграциями. Чо он то не отрабатывает?

2022-10-17 19:24 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/model/Position.java
> +        created = LocalDateTime.parse(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
Я не пойму, в чем проблема сделать
`created = LocalDateTime.now();` ?

2022-10-17 19:36 UTC, iLesnoy commented on src/test/resources/init.sql
> +create table roles
отрабатал; вариант со скриптом доп рассматривал

2022-10-17 19:38 UTC, viktor-dobroselsky commented on src/test/resources/init.sql
> +create table roles
Отвыкай мусорить в коде. Все, что не нужно - выпиливай

2022-10-19 16:23 UTC, viktor-dobroselsky approved these changes

2022-10-19 16:23 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/service/dto/CategoryDto.java
> +    @Pattern(regexp = "^[\\p{Alpha}А-Яа-я]{2,36}$")
Лучше разделяй Size и регекспу. Регекспу и так ну очень тяжело читать, так что лишней логикой нагружать ее не надо

2022-10-19 16:23 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/service/dto/CategoryDto.java
> +@JsonPropertyOrder({"id", "name","parentCategory", "description"})
Думаю, тебе ордер вообще не обязателен. Пусть будет, но, как по мне, это избыточно

2022-10-19 16:23 UTC, viktor-dobroselsky commented on src/main/java/com/petrovskiy/mds/service/dto/CustomPage.java
> +    @JsonProperty("total_pages")
Опять проблема с неймингом. Где-то кэмел, гдето андерскор, где-то что-то еще. Спринг с джексоном достаточно умный, чтобы нормально конвертировать твои поля без указания `@JsonProperty`. Вообще ее стоит использовать в явном виде только если тебе нужно действительно хитрожопое название поля. Чем меньше ты напишешь кода и аннотаций - тем проще твой код будет восприниматься

2022-10-19 16:23 UTC, viktor-dobroselsky commented on src/test/java/com/petrovskiy/mds/dao/impl/UserServiceIntegrationTest.java
> +@RunWith(SpringRunner.class)
А эта аннотация тебе точно нужна?

2022-10-19 16:35 UTC, iLesnoy commented on src/main/java/com/petrovskiy/mds/service/dto/CategoryDto.java
> +    @Pattern(regexp = "^[\\p{Alpha}А-Яа-я]{2,36}$")
ok

2022-10-20 09:01 UTC, merged