Develop
iLesnoy/Intern pull request #17
Opened 2022-12-07 07:31 UTC by iLesnoy

mongo

2022-12-09 08:06 UTC, viktor-dobroselsky requested changes

2022-12-09 08:06 UTC, viktor-dobroselsky commented on companies-api/src/main/java/com/petrovskiy/mds/model/Company.java
> +@RedisHash("companies")
Ох, не рекомендую тебе кэшировать сущность хибернейта. Может возникнуть тьма проблем с персистентным контекстом при неаккуратных движениях

2022-12-09 08:06 UTC, viktor-dobroselsky commented on item-api/src/main/java/com/petrovskiy/mds/dao/impl/ItemDaoImpl.java
> +        /*Pageable pageable = PageRequest.of(0, 10);
Мусор в коде

2022-12-28 07:32 UTC, Versach commented
У тебя конфликты тут

2022-12-28 07:33 UTC, Versach commented
Чтобы решить их нужно подмержить сперва мастер в твою ветку с пулом и разрешить их

2022-12-28 09:20 UTC, merged